let mapleader = ","
call pathogen#infect()

set autoindent
set encoding=utf-8
set expandtab
set hidden
set history=300     " Number of commands to remember
set ignorecase      " Ignore case when searching
set incsearch
set linebreak       " Break lines when appropriate
set mouse=a
set nocompatible    " Allow vim-only settings even if they break vi keybindings.
set number          " Show line numbers
set scrolloff=2
set shiftwidth=2
set showcmd
set smartcase       " Only ignore case when all lowercase
set smartindent
set smarttab
set softtabstop=2
set tabstop=2
set wildmenu

"------  Visual Options  ------
set guioptions-=T           "remove toolbar
set ruler                   "Displays cursor position on bottom right of screen
set statusline=%<%f\ %h%m%r%=%{fugitive#statusline()}\ \ %-14.(%l,%c%V%)\ %P
set background=dark
colorscheme desertink
syntax on

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'

let g:syntastic_phpcs_conf="--standard=Drupal --extensions=php,module,inc,install,test,profile,theme"

let php_sql_query = 1
let php_parent_error_close = 1
" let php_folding = 1

"------  PHP debugging  ------
map <F11> :DbgStepInto<CR>
map <F10> :DbgStepOver<CR>
map <S-F11> :DbgStepOut<CR>
map <F5> :DbgRun<CR>
map <S-F5> :DbgDetach<CR>
map <F8> :DbgToggleBreakpoint<CR>

"------  Syntax highlighting  ------
if has("autocmd")
  " Drupal's PHP file extensions
  autocmd BufRead,BufNewFile *.module,*.install,*.test,*.inc,*.profile,*.view,*.engine set filetype=drupal.php
  autocmd BufRead,BufNewFile *.info,*.make set filetype=ini
  autocmd Bufread,BufNewFile *.feature set filetype=cucumber
endif

" When in split screen, map <C-LeftArrow> and <C-RightArrow> to switch panes.
nn [1;5D <C-W>w
nn [1;5C <C-W>W

" Select just-pasted text.
nnoremap gp `[v`]

" Bubble single lines
nmap <C-Up> ddhP
nmap <C-Down> ddp
" Bubble multiple lines
vmap <C-Up> xkP`[V`]
vmap <C-Down> xp`[V`]

" Switch movement keys for Colemak so they're not super confusing.
set langmap=hk,jh,kj

" Useful trick when I've forgotten to sudo before editing a file.
" Source: https://github.com/cypher/dotfiles/blob/master/vimrc
cmap w!! w !sudo tee % >/dev/null

" PHP dictionary for autocompletion
set dict +=~/.vim/dictionaries/PHP.dict
set dict +=~/.vim/dictionaries/drupal6.dict

" Highlight redundant whitespaces and tabs.
highlight RedundantSpaces ctermbg=red guibg=red
match RedundantSpaces /\s\+$\| \+\ze\t\|\t/
