call pathogen#infect()

set autoindent
set encoding=utf-8
set expandtab
set hidden
set history=300     " Number of commands to remember
set incsearch
set ignorecase      " Ignore case when searching
set smartcase       " Only ignore case when all lowercase
set linebreak       " Break lines when appropriate
set mouse=a
set number          " Show line numbers
set nocompatible    " Allow vim-only settings even if they break vi keybindings.
set scrolloff=2
set shiftwidth=2
set showcmd
set smartindent
set smarttab
set tabstop=2
set wildmenu

"------  Visual Options  ------
set guioptions-=T           "remove toolbar
set ruler                   "Displays cursor position on bottom right of screen
set statusline=%<%f\ %h%m%r%=%{fugitive#statusline()}\ \ %-14.(%l,%c%V%)\ %P
set background=dark
colorscheme desertink
syntax on


set wildignore+=*/.git/*,*/.hg/*,*/.svn/*

let mapleader = " "

let php_sql_query = 1
let php_parent_error_close = 1
" let php_folding = 1

let g:debuggerMaxDepth = 5
let g:debuggerMiniBufExpl = 1

if has("autocmd")
  " Drupal's PHP file extensions
  augroup module
    autocmd BufRead,BufNewFile *.engine set filetype=php
    autocmd BufRead,BufNewFile *.inc set filetype=php
    autocmd BufRead,BufNewFile *.install set filetype=php
    autocmd BufRead,BufNewFile *.module set filetype=php
    autocmd BufRead,BufNewFile *.profile set filetype=php
    autocmd BufRead,BufNewFile *.test set filetype=php
  augroup END
  autocmd BufRead,BufNewFile *.make set filetype=ini
  autocmd BufRead,BufNewFile *.info set filetype=ini
endif

" When in split screen, map <C-LeftArrow> and <C-RightArrow> to switch panes.
nn [1;5D <C-W>w
nn [1;5C <C-W>W

" Bubble single lines
nmap <C-Up> ddhP
nmap <C-Down> ddp
" Bubble multiple lines
vmap <C-Up> xkP`[V`]
vmap <C-Down> xp`[V`]

" Switch movement keys for Colemak so they're not super confusing.
set langmap=hk,jh,kj

" Useful trick when I've forgotten to sudo before editing a file.
" Source: https://github.com/cypher/dotfiles/blob/master/vimrc
cmap w!! w !sudo tee % >/dev/null

" PHP dictionary for autocompletion
set dict +=~/.vim/dictionaries/PHP.dict
set dict +=~/.vim/dictionaries/drupal6.dict

" Highlight redundant whitespaces and tabs.
highlight RedundantSpaces ctermbg=red guibg=red
match RedundantSpaces /\s\+$\| \+\ze\t\|\t/
