execute pathogen#infect()
set nocompatible



" Bundle 'tpope/vim-sensible'

" Bundle 'gregsexton/gitv'

" Bundle 'mileszs/ack.vim'

" Bundle 'tpope/vim-rails'
" Bundle 'thoughtbot/vim-rspec'

" Bundle 'BlakeWilliams/vim-single-cursor-line'

set wildignore+=*tmp/*,*.so,*.swp,*.zip
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'

set list
set history=300      " Remember this many commands
set scrolloff=2      " Scroll 2 lines before bottom/top
set softtabstop=2
set tabstop=2
set shiftwidth=2
set expandtab
set wildmenu

set linebreak       " Break lines when appropriate
set mouse=a
set showcmd
set smartcase       " Only ignore case when all lowercase
set smartindent
set smarttab

let mapleader = ","

set laststatus=2   " Status line always, not just when split.
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_left_sep = '⮀'
let g:airline_left_alt_sep = '⮁'
let g:airline_right_sep = '⮂'
let g:airline_right_alt_sep = '⮃'
let g:airline_symbols.branch = '⭠'
let g:airline_symbols.readonly = '⭤'
let g:airline_symbols.linenr = '⭡'

"------  Visual Options ------
"set guioptions-=T    " Remove toolbar.
set guifont=Inconsolata-dz\ for\ Powerline\ 10
set guifont=Monospace\ 10
set guifont=Mensch\ for\ Powerline\ 10
set guifont=Menlo\ for\ Powerline\ 10
set guifont=Source\ Code\ Pro\ for\ Powerline:h14

set statusline=%<%f\ %h%m%r%=%{fugitive#statusline()}\ \ %-14.(%l,%c%V%)\ %P
set background=dark

colorscheme desertink
syntax on
filetype plugin indent on

let php_sql_query = 1
let php_parent_error_close = 1

"------  Syntax highlighting  ------
if has("autocmd")
  autocmd BufRead,BufNewFile *.feature set filetype=cucumber
  autocmd BufRead,BufNewFile *.pp set filetype=ruby
endif

"------ active buffer's path
cnoremap <expr> %%  getcmdtype() == ':' ? expand('%:h') . '/' : '%%'

"------ Colemak keyboard layout mappings ------
map <Up> gh
map <Down> gk

" Source: http://forum.colemak.com/viewtopic.php?pid=184#p184
noremap K J
noremap J K
noremap h k
noremap j h
noremap k j
noremap gh gk
noremap gj gh
noremap gk gj
noremap zh zk
"zK does not exist
noremap zj zh
noremap zJ zH
noremap zk zj
"zJ does not exist
noremap z<Space> zl
noremap z<S-Space> zL
noremap z<BS> zh
noremap z<S-BS> zH
noremap <C-w>h <C-w>k
noremap <C-w>H <C-w>K
noremap <C-w>j <C-w>h
noremap <C-w>J <C-w>H
noremap <C-w>k <C-w>j
noremap <C-w>K <C-w>J
noremap <C-w><Space> <C-w>l
noremap <C-w><S-Space> <C-w>L
noremap <C-w><S-BS> <C-w>H

" Easy split navigation, adapted from
" https://github.com/sjl/dotfiles/blob/master/vim/vimrc#L509.
noremap <C-h> <C-w>k
noremap <C-j> <C-w>h
noremap <C-k> <C-w>j
noremap <C-l> <C-w>l

" Select just-pasted text.
nnoremap gp `[v`]
