<?php

define('MIGRATE_ACCESS_BASIC', 'migration information');

function migrate_ui_help($path, $arg) {
  switch ($path) {
    case 'admin/migrate':
      return t('The current status of each migration defined in this system. Click on a migration name for details on its configuration.');
  }
}

/**
 * Implementation of hook_perm().
 */
function migrate_ui_perm() {
  return array(MIGRATE_ACCESS_BASIC);
}

/**
 * Implementation of hook_menu().
 */
function migrate_menu() {
  $items = array();

  $items['admin/migrate'] = array(
    'title' => 'Migrate',
    'description' => 'Monitor the creation of Drupal content from source data',
    'page callback' => 'migrate_ui_dashboard',
    'access arguments' => array(MIGRATE_ACCESS_BASIC),
    'file' => 'migrate_ui/migrate_ui.pages.inc',
  );
  $items['admin/migrate/messages/%migration'] = array(
    'title callback' => 'migration_title',
    'title arguments' => array(3),
    'description' => 'View messages from a migration',
    'page callback' => 'migrate_ui_messages',
    'page arguments' => array(3),
    'access arguments' => array(MIGRATE_ACCESS_BASIC),
    'file' => 'migrate_ui/migrate_ui.pages.inc',
  );
  $items['admin/migrate/%migration'] = array(
    'title callback' => 'migration_title',
    'title arguments' => array(2),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migrate_migration_info', 2),
    'access arguments' => array(MIGRATE_ACCESS_BASIC),
    'file' => 'migrate_ui/migrate_ui.pages.inc',
  );

  if (FALSE) {
    // Not working yet
    migrate_ui_menu_add($items);
  }

  return $items;
}

// A menu load callback.
function migration_load($machine_name) {
  if ($machine_name) {
    $class_name = $machine_name . 'Migration';
    return Migration::getInstance($class_name);
  }
}

function migration_title($migration) {
  if (is_string($migration)) {
    $migration = migration_load($migration);
  }
  return $migration->getMachineName();
}
